services:
  - type: web
    name: video-enhancer-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
      - key: MAX_FILE_SIZE
        value: "100MB"
      - key: FFMPEG_PATH
        value: "/usr/bin/ffmpeg"
      - key: REALESRGAN_PATH
        value: "/usr/local/bin/realesrgan"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    repo: https://github.com/yourusername/online-video-enhancer
    disk:
      name: videos
      mountPath: /opt/render/project/src/videos
      sizeGB: 10 